name: haugiang_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  fluttertoast: ^8.2.2
  flutter_barcode_scanner: ^2.0.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  scroll_to_index: ^3.0.1
  anchor_scroll_controller: ^0.4.3
  scrollable_positioned_list: ^0.3.8
  flutter_marquee: ^2.0.1
  flutter_typeahead: ^4.6.2

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.6.2


flutter: 
  uses-material-design: true
  assets:
    - assets/images/  # Đường dẫn tới thư mục chứa hình ảnh
